name: (local test) Release Delphi Utils

on:
  push:
    branches: [ prod ]
    tags: [ delphi_utils/* ]
  workflow_dispatch:

jobs:
  create_delphi_utils_release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: _delphi_utils_python
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.CMU_DELPHI_DEPLOY_MACHINE_SSH }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Extract version
        id: extract_version
        run: |
          python -m pip install bump2version
          echo -n "::set-output name=version::"
          bump2version --dry-run --list patch | grep ^current_version | sed -r s,"^.*=",,
    outputs:
      version: ${{ steps.extract_version.outputs.version }}

  upload_pypi:
    needs: create_delphi_utils_release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: _delphi_utils_python
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install testing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pydocstyle wheel twine
      - name: Install
        run: |
          make install
      - name: Release
        run: |
          make release
      - uses: actions/upload-artifact@v2
        with:
          name: delphi_utils
          path: _delphi_utils_python/dist/*.tar.gz

  sync_main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: main
          ssh-key: ${{ secrets.CMU_DELPHI_DEPLOY_MACHINE_SSH }}
      - name: Reset main branch
        run: |
          git fetch origin prod:prod
          git reset --hard prod
      - name: Create pull request into main
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CMU_DELPHI_DEPLOY_MACHINE_PAT }}
          branch: bot/sync-prod-main
          commit-message: 'chore: sync prod-main'
          base: main
          title: 'chore: sync prod->main'
          labels: chore
          reviewers: krivard
          assignees: krivard
          body: |
            Syncing Prod->Main.
