name: Suggest Delphi Utils Release

on:
  push:
    branches: [ prod ]
    paths: [ _delphi_utils_python/** ]
  pull_request:
    branches: [ prod ]
    paths: [ _delphi_utils_python/** ]
  workflow_dispatch:

jobs:
  suggest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.CMU_DELPHI_DEPLOY_MACHINE_SSH }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Extract version
        id: extract_version
        run: |
          python -m pip install bump2version
          echo -n "::set-output name=version::"
          bump2version --dry-run --list patch | grep ^current_version | sed -r s,"^.*=",,
      - name: Create an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_VERSION: ${{ steps.extract_version.outputs.version }}
        with:
          filename: .github/issue-suggest-utils-release-template.md
